Create headings for sidebar pages
nextcloud/activity pull request #1081
Opened 2023-02-10 13:39 UTC by JuliaKirschenheuter

Relates to https://github.com/nextcloud/server/issues/35626

After:

![Screenshot from 2023-02-10 14-37-52](https://user-images.githubusercontent.com/6078378/218105636-590b0ee2-9c22-4059-8240-0a1a70621ace.png)
![Screenshot from 2023-02-10 14-38-16](https://user-images.githubusercontent.com/6078378/218105711-0ee62517-b61b-4d1f-bb09-04228e01bc8b.png)

2023-02-10 14:15 UTC, nickvergessen requested changes

2023-02-10 14:15 UTC, nickvergessen commented on js/script.js
> +			document.getElementById('pageHeadingLevel2').textContent = `${t('active', 'Subsection: ')} ${navigationLink.text().trim()}`;
String concatenation breaks translations:

https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#important-notes

2023-02-10 14:23 UTC, nickvergessen commented
Where is the section defined. I assume a generic PR in server? How is ensured that it is not added when there is an h1 already.
Why are the words "Section" and "Subsection" added? That feels so wrong and unneeded.
If it would be helpful we could make activity filters have defining a "Activitiy by others" h2 title additional to the link name.
But the current wording really sound like a quirk/hack?🤔

2023-02-10 14:55 UTC, JuliaKirschenheuter commented
/backport to stable25

2023-03-03 12:59 UTC, JuliaKirschenheuter commented
/backport to stable26

2023-03-03 21:49 UTC, Pytal approved these changes

2023-03-06 16:39 UTC, artonge approved these changes

2023-03-08 08:22 UTC, merged