Remove unneeded margin after paragraphs
nextcloud/activity pull request #1231
Opened 2023-06-29 09:13 UTC by JuliaKirschenheuter

Fixes https://github.com/nextcloud/server/issues/36978

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![image](https://github.com/nextcloud/activity/assets/6078378/2aca6e5f-6b77-46b2-8348-0056854e7529) | ![Screenshot from 2023-06-29 11-04-42](https://github.com/nextcloud/activity/assets/6078378/e4c77bd2-88fb-4802-9f51-c850d9047cbb)

Works with:

- [x] Check Dashboard widgets with ARCToolkit
- [x] Check Dashboard widgets with Text spacing editor

2023-06-29 09:38 UTC, artonge requested changes
Looks like this is using https://github.com/nextcloud/nextcloud-vue-dashboard which is deprecated.

Can you try to use the components from https://github.com/nextcloud/nextcloud-vue?

2023-06-29 09:38 UTC, artonge commented on src/views/Dashboard.vue
> +				class="activity_panel-item"
```suggestion
				class="activity-panel__item"
```

2023-06-29 10:33 UTC, JuliaKirschenheuter commented
> Looks like this is using https://github.com/nextcloud/nextcloud-vue-dashboard which is deprecated.
Oh, yes, i've seen it some time ago ;( but missed it now. i will have a look

2023-07-01 19:42 UTC, susnux approved these changes
Looks good

2023-07-01 20:57 UTC, Fenn-CS approved these changes

2023-07-06 21:21 UTC, Pytal approved these changes

2023-07-07 15:56 UTC, susnux commented
(rebased)
Looks good, just to squash the `!fixup ` commits and then this should ready to go :)

2023-08-11 22:56 UTC, Pytal approved these changes

2023-08-12 01:37 UTC, susnux approved these changes

2023-08-15 11:00 UTC, artonge commented
Rebased

2023-08-15 11:20 UTC, AndyScherzinger commented
@artonge Can I safely force-merge?

2023-08-15 12:53 UTC, merged