add comment functionality to activity tab
nextcloud/activity pull request #1387
Opened 2023-10-30 17:41 UTC by sorbaugh

Signed-off-by: Stephan Orbaugh <stephan.orbaugh@nextcloud.com>

2023-11-02 14:49 UTC, artonge requested changes
As the Comments tab need to be displayed if the activity app is disabled, the current approach leads to a lot of duplicate code.

A better approach would be to create an API so that the Comments app can add content to the actvity stream.

2023-11-02 14:49 UTC, artonge commented on src/components/Moment.vue
> +<!-- TODO: Move to vue components -->
TODO

2023-11-02 14:49 UTC, artonge commented on src/components/Moment.vue
Licence is missing

2023-11-02 14:49 UTC, artonge commented on src/components/Moment.vue
> +	name: 'Moment',
Name is too generic

2023-11-02 14:49 UTC, artonge commented on src/mixins/CommentMixin.js
> +				// this.logger.debug('New comment posted', { commentsType: this.commentsType, ressourceId: this.ressourceId, newComment })
Debug ?

2023-11-02 14:49 UTC, artonge commented on src/sidebar.js
> +		ActivityTabView = ActivityTabView ?? Vue.extend(ActivityTab)
Won't this revert this optimisation?
https://github.com/nextcloud/activity/pull/1363

2023-11-15 12:52 UTC, closed without merging

2023-11-15 12:52 UTC, susnux commented
Closing in favor of https://github.com/nextcloud/activity/pull/1416