WIP: Port settings to vue
nextcloud/activity pull request #861
Opened 2022-08-01 14:01 UTC by CarlSchwan

2022-08-01 16:14 UTC, CarlSchwan commented
@szaimen pointed out to me https://github.com/nextcloud/activity/pull/589, I'll try to merge both efforts

2022-08-02 09:46 UTC, jancborchardt requested changes
Nice! Only details:
- Can you move the Mail/Push checkbox columns to the left again, so there’s not so much whitespace and it’s all nicely left-aligned like before? See screenshot below
- I can’t fully tell from the code – are the "Files", "Calendar, contacts and tasks" and "Other activities" marked up as h3?

![image](https://user-images.githubusercontent.com/925062/182345220-bf6f9ba8-6c0a-4d07-8d36-0021a1d59826.png)

2022-08-02 11:40 UTC, nimishavijay commented
> Can you move the Mail/Push checkbox columns to the left again, so there’s not so much whitespace and it’s all nicely left-aligned like before? See screenshot below

I actually like it how @CarlSchwan did it, before the text alignment was a bit messy.
What do you think about keeping it like this but decreasing the space between the text and checkboxes? @jancborchardt

2022-08-02 20:32 UTC, CarlSchwan commented
> Nice! Only details:
> 
>     * Can you move the Mail/Push checkbox columns to the left again, so there’s not so much whitespace and it’s all nicely left-aligned like before? See screenshot below

My main motivation to moving the checkbox to the right was to simplify the layout for screenreader (we don't have this two level of headers) and since the content is read from the left to the right the screenreader will first read the description of the checkbox and then tell the state of the mail notification and push notification for each row.

This also solves some alignment issues with the content not at all left aligned. See screenshot

![align](https://user-images.githubusercontent.com/23653902/182467250-62fe0bd5-61cd-4cce-89a0-c626038cbb9e.png)

> 
>     * I can’t fully tell from the code – are the "Files", "Calendar, contacts and tasks" and "Other activities" marked up as h3?

Done, this is now using h3

2022-08-03 19:51 UTC, jancborchardt commented
Cool, sounds good @CarlSchwan – do you mind decreasing the space between text and checkboxes a bit like @nimishavijay proposed? :)

2022-08-19 17:50 UTC, CarlSchwan commented
I still need one approval ;)

2022-08-19 18:01 UTC, skjnldsv approved these changes

2022-08-19 21:13 UTC, AndyScherzinger approved these changes

2022-08-19 22:04 UTC, merged