Rename user to people
nextcloud/activity pull request #927
Opened 2022-09-21 16:44 UTC by PVince81

2022-09-21 17:05 UTC, artonge requested changes

2022-09-21 17:05 UTC, artonge commented on package.json
> +  "description": "This application people users to view a log of activities about them or about files.",
```suggestion
  "description": "This application enables people to view a log of activities about them or about files.",
```

2022-09-21 17:08 UTC, nickvergessen commented on appinfo/info.xml
> +	<summary>This application enables people to view a log of activities about them or about files.</summary>
```suggestion
	<summary>This application enables people to view a log of activities about them, their files or other data.</summary>
```

2022-09-21 17:11 UTC, nickvergessen commented on appinfo/info.xml
> +		This sets the type of activity to record, as well as whether the person sees their own activities,
The whole description is so wrong, but let's keep it for now and fix it next time

2022-09-21 17:34 UTC, artonge approved these changes

2022-09-22 05:30 UTC, nickvergessen approved these changes

2022-09-26 11:57 UTC, jancborchardt approved these changes
Looks good!

2022-09-26 13:39 UTC, nickvergessen commented
String freeze, can only be merged after 18th October

2022-11-18 06:24 UTC, nickvergessen commented
Rebased and now it's time to merge

2022-11-18 06:30 UTC, merged